url_prefix: https://dev.shosato.jp
mongo_url: 'mongodb://localhost:8070/'
port: 5426

line:
  __ENV__access_token: KYUKOU_LINE_ACCESS_TOKEN
  __ENV__channel_secret: KYUKOU_LINE_CHANNEL_SECRET
  channel_id: 1622536568

line_notify:
  client_id: UC00AINvR0Jtm3mThDVZPS
  __ENV__client_secret: KYUKOU_LINE_NOTIFY_client_SECRET
  redirect_uri: /api/v1/line/notify

twitter:
  callback_path: /api/v1/twitter/callback
  webhook_path: /api/v1/twitter/webhook
  __ENV__consumer_key: KYUKOU_TWITTER_CONSUMER_KEY
  __ENV__consumer_key_secret: KYUKOU_TWITTER_CONSUMER_KEY_SECRET
  __ENV__access_token: KYUKOU_TWITTER_ACCESS_TOKEN
  __ENV__access_token_secret: KYUKOU_TWITTER_ACCESS_TOKEN_SECRET
  account_activity_api_env: kyukou

email:
  __ENV__password: KYUKOU_LINE_CHANNEL_SECRET
  smtp_server: yellowcoyote4.sakura.ne.jp
  smtp_port: 587
  from_addr: kyukou@shosato.jp
  
google:
  __ENV__google_client_secret: KYUKOU_GOOGLE_CLIENT_SECRET
  client_id: 723530674332-g9bq3lq6e921pip895vk6mgg91fhui4l.apps.googleusercontent.com
  scope: 'email profile openid https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/calendar.events'
  access_type: offline
  prompt: consent # select_account
  response_type: code

public_dir: ./web/public
index: index.html

default_notify:
  type: day
  offset: -97200

__ENV__hash_salt: KYUKOU_HASH_SALT
logfile: ../log/kyukou.log
log_level: 1